window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.cs = {
    languageLabel: 'Jazyk',
    historyTitle: 'Historie',
    clear: 'Vyčistit',
    blueprintStringTitle: 'Řetězec blueprintu',
    blueprintPlaceholder: 'Vložte řetězec blueprintu...',
    decode: 'Decode',
    delete: 'Smazat',
    jsonEditorTitle: 'JSON editor',
    searchPlaceholder: 'Hledat v JSON...',
    find: 'Najít',
    next: 'Další',
    prev: 'Předchozí',
    replace: 'Nahradit',
    replaceFromPlaceholder: 'Text k nahrazení...',
    replaceToPlaceholder: 'Nahradit za...',
    replaceAll: 'Nahradit vše',
    encode: 'Encode',
    copy: 'Kopírovat',
    supportText: 'Vytvořeno s podporou telegramové komunity FCTostin',
    steamGuideHtml: 'Steam návod: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Dekodér/enkodér blueprintu</a>',
    historyRestoreTitle: 'Obnovit blueprint',
    historyEmpty: 'Prázdné',
    matchesNotFound: 'Nenalezeny žádné shody!',
    replaceEnterText: 'Zadejte text k nahrazení.',
    replaceNotFound: 'Text k nahrazení nebyl nalezen.',
    replaceDone: 'Nahrazení dokončeno!',
    enterBlueprint: 'Zadejte řetězec blueprintu',
    decodeFailed: 'Nepodařilo se dekódovat blueprint:',
    encodingError: 'Chyba kódování:',
    jsonEditorEmpty: 'JSON editor je prázdný!',
    encodeError: 'Chyba kódování: Neplatný formát JSON.',
    copied: 'Zkopírováno!',
};
