window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.en = {
    languageLabel: 'Language',
    historyTitle: 'History',
    clear: 'Clear',
    blueprintStringTitle: 'Blueprint string',
    blueprintPlaceholder: 'Paste blueprint string...',
    decode: 'Decode',
    delete: 'Delete',
    jsonEditorTitle: 'JSON editor',
    searchPlaceholder: 'Search in JSON...',
    find: 'Find',
    next: 'Next',
    prev: 'Previous',
    replace: 'Replace',
    replaceFromPlaceholder: 'Text to replace...',
    replaceToPlaceholder: 'Replace with...',
    replaceAll: 'Replace all',
    encode: 'Encode',
    copy: 'Copy',
    supportText: 'Created with support from the FCTostin Telegram community',
    steamGuideHtml: 'Steam guide: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Blueprint decoder/encoder</a>',
    historyRestoreTitle: 'Restore blueprint',
    historyEmpty: 'Empty',
    matchesNotFound: 'No matches found!',
    replaceEnterText: 'Please enter text to replace.',
    replaceNotFound: 'Text to replace was not found.',
    replaceDone: 'Replacement completed!',
    enterBlueprint: 'Please enter a blueprint string',
    decodeFailed: 'Failed to decode blueprint:',
    encodingError: 'Encoding error:',
    jsonEditorEmpty: 'JSON editor is empty!',
    encodeError: 'Encoding error: Invalid JSON format.',
    copied: 'Copied!',
};
