window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.fr = {
    languageLabel: 'Langue',
    historyTitle: 'Historique',
    clear: 'Effacer',
    blueprintStringTitle: 'Chaîne blueprint',
    blueprintPlaceholder: 'Collez la chaîne blueprint...',
    decode: 'Decode',
    delete: 'Supprimer',
    jsonEditorTitle: 'Éditeur JSON',
    searchPlaceholder: 'Rechercher dans JSON...',
    find: 'Trouver',
    next: 'Suivant',
    prev: 'Précédent',
    replace: 'Remplacer',
    replaceFromPlaceholder: 'Texte à remplacer...',
    replaceToPlaceholder: 'Remplacer par...',
    replaceAll: 'Tout remplacer',
    encode: 'Encode',
    copy: 'Copier',
    supportText: 'Créé avec le soutien de la communauté Telegram FCTostin',
    steamGuideHtml: 'Guide Steam : <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Décodeur/encodeur blueprint</a>',
    historyRestoreTitle: 'Restaurer le blueprint',
    historyEmpty: 'Vide',
    matchesNotFound: 'Aucune correspondance trouvée !',
    replaceEnterText: 'Veuillez saisir le texte à remplacer.',
    replaceNotFound: 'Le texte à remplacer est introuvable.',
    replaceDone: 'Remplacement terminé !',
    enterBlueprint: 'Veuillez saisir une chaîne blueprint',
    decodeFailed: 'Échec du décodage du blueprint :',
    encodingError: 'Erreur d\'encodage :',
    jsonEditorEmpty: 'L\'éditeur JSON est vide !',
    encodeError: 'Erreur d\'encodage : format JSON invalide.',
    copied: 'Copié !',
};
