window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.ja = {
    languageLabel: '言語',
    historyTitle: '履歴',
    clear: 'クリア',
    blueprintStringTitle: 'ブループリント文字列',
    blueprintPlaceholder: 'ブループリント文字列を貼り付け...',
    decode: 'Decode',
    delete: '削除',
    jsonEditorTitle: 'JSON エディター',
    searchPlaceholder: 'JSON を検索...',
    find: '検索',
    next: '次へ',
    prev: '前へ',
    replace: '置換',
    replaceFromPlaceholder: '置換するテキスト...',
    replaceToPlaceholder: '置換後のテキスト...',
    replaceAll: 'すべて置換',
    encode: 'Encode',
    copy: 'コピー',
    supportText: 'FCTostin Telegram コミュニティの支援で作成',
    steamGuideHtml: 'Steam ガイド：<a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">ブループリントデコーダー/エンコーダー</a>',
    historyRestoreTitle: 'ブループリントを復元',
    historyEmpty: '空',
    matchesNotFound: '一致が見つかりません！',
    replaceEnterText: '置換するテキストを入力してください。',
    replaceNotFound: '置換対象のテキストが見つかりません。',
    replaceDone: '置換が完了しました！',
    enterBlueprint: 'ブループリント文字列を入力してください',
    decodeFailed: 'ブループリントのデコードに失敗しました:',
    encodingError: 'エンコードエラー:',
    jsonEditorEmpty: 'JSON エディターが空です！',
    encodeError: 'エンコードエラー: JSON 形式が無効です。',
    copied: 'コピーしました！',
};
