window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.kk = {
    languageLabel: 'Тіл',
    historyTitle: 'Тарих',
    clear: 'Тазалау',
    blueprintStringTitle: 'Сызба жолы',
    blueprintPlaceholder: 'Сызба жолын енгізіңіз...',
    decode: 'Decode',
    delete: 'Жою',
    jsonEditorTitle: 'JSON редакторы',
    searchPlaceholder: 'JSON ішінен іздеу...',
    find: 'Табу',
    next: 'Келесі',
    prev: 'Алдыңғы',
    replace: 'Ауыстыру',
    replaceFromPlaceholder: 'Ауыстырылатын мәтін...',
    replaceToPlaceholder: 'Немен ауыстыру...',
    replaceAll: 'Барлығын ауыстыру',
    encode: 'Encode',
    copy: 'Көшіру',
    supportText: 'FCTostin Telegram қауымдастығының қолдауымен жасалған',
    steamGuideHtml: 'Steam нұсқаулығы: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Сызба декодері/энкодері</a>',
    historyRestoreTitle: 'Сызбаны қалпына келтіру',
    historyEmpty: 'Бос',
    matchesNotFound: 'Сәйкестік табылмады!',
    replaceEnterText: 'Ауыстыратын мәтінді енгізіңіз.',
    replaceNotFound: 'Ауыстыру мәтіні табылмады.',
    replaceDone: 'Ауыстыру аяқталды!',
    enterBlueprint: 'Сызба жолын енгізіңіз',
    decodeFailed: 'Сызбаны декодтау сәтсіз:',
    encodingError: 'Кодтау қатесі:',
    jsonEditorEmpty: 'JSON редакторы бос!',
    encodeError: 'Кодтау қатесі: JSON форматы қате.',
    copied: 'Көшірілді!',
};
