window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.nl = {
    languageLabel: 'Taal',
    historyTitle: 'Geschiedenis',
    clear: 'Wissen',
    blueprintStringTitle: 'Blueprint-string',
    blueprintPlaceholder: 'Plak blueprint-string...',
    decode: 'Decode',
    delete: 'Verwijderen',
    jsonEditorTitle: 'JSON-editor',
    searchPlaceholder: 'Zoeken in JSON...',
    find: 'Zoeken',
    next: 'Volgende',
    prev: 'Vorige',
    replace: 'Vervangen',
    replaceFromPlaceholder: 'Tekst om te vervangen...',
    replaceToPlaceholder: 'Vervangen door...',
    replaceAll: 'Alles vervangen',
    encode: 'Encode',
    copy: 'Kopiëren',
    supportText: 'Gemaakt met steun van de FCTostin Telegram-community',
    steamGuideHtml: 'Steam-handleiding: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Blueprint decoder/encoder</a>',
    historyRestoreTitle: 'Blueprint herstellen',
    historyEmpty: 'Leeg',
    matchesNotFound: 'Geen overeenkomsten gevonden!',
    replaceEnterText: 'Voer tekst in om te vervangen.',
    replaceNotFound: 'Tekst om te vervangen niet gevonden.',
    replaceDone: 'Vervanging voltooid!',
    enterBlueprint: 'Voer een blueprint-string in',
    decodeFailed: 'Blueprint decoderen mislukt:',
    encodingError: 'Encoderingsfout:',
    jsonEditorEmpty: 'JSON-editor is leeg!',
    encodeError: 'Encoderingsfout: Ongeldig JSON-formaat.',
    copied: 'Gekopieerd!',
};
