window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.pl = {
    languageLabel: 'Język',
    historyTitle: 'Historia',
    clear: 'Wyczyść',
    blueprintStringTitle: 'Ciąg blueprintu',
    blueprintPlaceholder: 'Wklej ciąg blueprintu...',
    decode: 'Decode',
    delete: 'Usuń',
    jsonEditorTitle: 'Edytor JSON',
    searchPlaceholder: 'Szukaj w JSON...',
    find: 'Znajdź',
    next: 'Następny',
    prev: 'Poprzedni',
    replace: 'Zamień',
    replaceFromPlaceholder: 'Tekst do zamiany...',
    replaceToPlaceholder: 'Zamień na...',
    replaceAll: 'Zamień wszystko',
    encode: 'Encode',
    copy: 'Kopiuj',
    supportText: 'Stworzone przy wsparciu społeczności Telegram FCTostin',
    steamGuideHtml: 'Poradnik Steam: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Dekoder/enkoder blueprintów</a>',
    historyRestoreTitle: 'Przywróć blueprint',
    historyEmpty: 'Pusto',
    matchesNotFound: 'Nie znaleziono dopasowań!',
    replaceEnterText: 'Wpisz tekst do zamiany.',
    replaceNotFound: 'Nie znaleziono tekstu do zamiany.',
    replaceDone: 'Zamiana zakończona!',
    enterBlueprint: 'Wpisz ciąg blueprintu',
    decodeFailed: 'Nie udało się zdekodować blueprintu:',
    encodingError: 'Błąd kodowania:',
    jsonEditorEmpty: 'Edytor JSON jest pusty!',
    encodeError: 'Błąd kodowania: Nieprawidłowy format JSON.',
    copied: 'Skopiowano!',
};
