window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.ru = {
    languageLabel: 'Язык',
    historyTitle: 'История',
    clear: 'Очистить',
    blueprintStringTitle: 'Строка чертежа',
    blueprintPlaceholder: 'Вставьте строку чертежа...',
    decode: 'Decode',
    delete: 'Удалить',
    jsonEditorTitle: 'JSON редактор',
    searchPlaceholder: 'Поиск в JSON...',
    find: 'Найти',
    next: 'Следующий',
    prev: 'Предыдущий',
    replace: 'Заменить',
    replaceFromPlaceholder: 'Текст для замены...',
    replaceToPlaceholder: 'Заменить на...',
    replaceAll: 'Заменить все',
    encode: 'Encode',
    copy: 'Скопировать',
    supportText: 'Создано при поддержке Телеграм сообщества FCTostin',
    steamGuideHtml: 'Руководство Steam: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Декодер/Енкодер чертежа</a>',
    historyRestoreTitle: 'Восстановить чертеж',
    historyEmpty: 'Пусто',
    matchesNotFound: 'Совпадений не найдено!',
    replaceEnterText: 'Пожалуйста, введите текст, который нужно заменить.',
    replaceNotFound: 'Текст для замены не найден.',
    replaceDone: 'Замена завершена!',
    enterBlueprint: 'Пожалуйста, введите строку чертежа',
    decodeFailed: 'Не удалось расшифровать чертеж:',
    encodingError: 'Ошибка кодирования:',
    jsonEditorEmpty: 'JSON редактор пуст!',
    encodeError: 'Ошибка кодирования: Неверный формат JSON.',
    copied: 'Скопировано!',
};
