window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.sv = {
    languageLabel: 'Språk',
    historyTitle: 'Historik',
    clear: 'Rensa',
    blueprintStringTitle: 'Blueprint-sträng',
    blueprintPlaceholder: 'Klistra in blueprint-sträng...',
    decode: 'Decode',
    delete: 'Ta bort',
    jsonEditorTitle: 'JSON-redigerare',
    searchPlaceholder: 'Sök i JSON...',
    find: 'Sök',
    next: 'Nästa',
    prev: 'Föregående',
    replace: 'Ersätt',
    replaceFromPlaceholder: 'Text att ersätta...',
    replaceToPlaceholder: 'Ersätt med...',
    replaceAll: 'Ersätt alla',
    encode: 'Encode',
    copy: 'Kopiera',
    supportText: 'Skapad med stöd från FCTostin Telegram-community',
    steamGuideHtml: 'Steam-guide: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Blueprint avkodare/kodare</a>',
    historyRestoreTitle: 'Återställ blueprint',
    historyEmpty: 'Tomt',
    matchesNotFound: 'Inga träffar hittades!',
    replaceEnterText: 'Ange text att ersätta.',
    replaceNotFound: 'Text att ersätta hittades inte.',
    replaceDone: 'Ersättning klar!',
    enterBlueprint: 'Ange en blueprint-sträng',
    decodeFailed: 'Misslyckades att avkoda blueprint:',
    encodingError: 'Kodningsfel:',
    jsonEditorEmpty: 'JSON-redigeraren är tom!',
    encodeError: 'Kodningsfel: Ogiltigt JSON-format.',
    copied: 'Kopierad!',
};
