window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.uk = {
    languageLabel: 'Мова',
    historyTitle: 'Історія',
    clear: 'Очистити',
    blueprintStringTitle: 'Рядок креслення',
    blueprintPlaceholder: 'Вставте рядок креслення...',
    decode: 'Decode',
    delete: 'Видалити',
    jsonEditorTitle: 'JSON редактор',
    searchPlaceholder: 'Пошук у JSON...',
    find: 'Знайти',
    next: 'Наступний',
    prev: 'Попередній',
    replace: 'Замінити',
    replaceFromPlaceholder: 'Текст для заміни...',
    replaceToPlaceholder: 'Замінити на...',
    replaceAll: 'Замінити все',
    encode: 'Encode',
    copy: 'Скопіювати',
    supportText: 'Створено за підтримки Telegram-спільноти FCTostin',
    steamGuideHtml: 'Steam керівництво: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">Декодер/Енкодер креслень</a>',
    historyRestoreTitle: 'Відновити креслення',
    historyEmpty: 'Порожньо',
    matchesNotFound: 'Збігів не знайдено!',
    replaceEnterText: 'Введіть текст для заміни.',
    replaceNotFound: 'Текст для заміни не знайдено.',
    replaceDone: 'Заміна завершена!',
    enterBlueprint: 'Введіть рядок креслення',
    decodeFailed: 'Не вдалося декодувати креслення:',
    encodingError: 'Помилка кодування:',
    jsonEditorEmpty: 'JSON редактор порожній!',
    encodeError: 'Помилка кодування: Невірний формат JSON.',
    copied: 'Скопійовано!',
};
