window.BP_TRANSLATIONS = window.BP_TRANSLATIONS || {};
window.BP_TRANSLATIONS.zh = {
    languageLabel: '语言',
    historyTitle: '历史记录',
    clear: '清空',
    blueprintStringTitle: '蓝图字符串',
    blueprintPlaceholder: '粘贴蓝图字符串...',
    decode: 'Decode',
    delete: '删除',
    jsonEditorTitle: 'JSON 编辑器',
    searchPlaceholder: '在 JSON 中搜索...',
    find: '查找',
    next: '下一个',
    prev: '上一个',
    replace: '替换',
    replaceFromPlaceholder: '要替换的文本...',
    replaceToPlaceholder: '替换为...',
    replaceAll: '全部替换',
    encode: 'Encode',
    copy: '复制',
    supportText: '在 FCTostin Telegram 社区支持下创建',
    steamGuideHtml: 'Steam 指南：<a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3478429132" target="_blank" rel="noreferrer">蓝图解码器/编码器</a>',
    historyRestoreTitle: '恢复蓝图',
    historyEmpty: '空',
    matchesNotFound: '未找到匹配项！',
    replaceEnterText: '请输入要替换的文本。',
    replaceNotFound: '未找到要替换的文本。',
    replaceDone: '替换完成！',
    enterBlueprint: '请输入蓝图字符串',
    decodeFailed: '无法解码蓝图：',
    encodingError: '编码错误：',
    jsonEditorEmpty: 'JSON 编辑器为空！',
    encodeError: '编码错误：JSON 格式无效。',
    copied: '已复制！',
};
